kind: ConfigMap
apiVersion: v1
metadata:
  name: deno-proxy
  namespace: deno
data:
  nginx-proxy.conf: >
    server {
      listen 80;
      location / {
        proxy_pass http://deno-api:8000;
      }
    }