 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: deno
   namespace: deno
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$1
 spec:
   rules:
   - host: deno-kube.io
     http:
       paths:
       - path: /
         backend:
           serviceName: deno-proxy
           servicePort: 80